---
- nome: Upgrade de todos os pacotes S.O
  yum:
    name: '*'
    state: latest
- name: instalação do glit client
  yum:
    name: git
    state: latest
- name: Configurar o Hosts lab ansible
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items: 
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01